permalink: /:year/:month/:day/:title/

# 站点设置
title: "Moilk Blog"
email: MoilkNepho@gmail.com
description: "Moilk的个人博客"
keywords: "Moilk"

# 用户信息设置
weibo_username: Moilknepho
github_username: MoilkNepho

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: false
highlighter: rouge



# 地址设置
baseurl: "/blog"
url: "https://moilk.org/blog"


# 分页设置
paginate: 6
paginate_path: "page:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# GitMent设置
gitment:
  enable: true
  githubID: MoilkNepho
  repo: blog
  ClientID: 39587457ab8aabd98d18
  ClientSecret: 14768f3ef851ddc213cd12c44655d10dd1dc025f
  lazy: true
